DROP TABLE IF EXISTS raw_sentences; --CHANGE LATER
CREATE TABLE raw_sentences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sentence TEXT NOT NULL,
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS tags;
CREATE TABLE tags (
  tag TEXT NOT NULL
);

DROP TABLE IF EXISTS verbs;
CREATE TABLE verbs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  verb TEXT NOT NULL,
  sense_id INTEGER NOT NULL,
  sense TEXT NOT NULL,
  args TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS annotated_sentences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  word TEXT NOT NULL,
  word_index INTEGER NOT NULL,
  sense TEXT,
  depth INTEGER NOT NULL,
  sentence_id INTEGER NOT NULL,
  annotater_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS annotated_nodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  word TEXT NOT NULL,
  word_index INTEGER NOT NULL,
  sense TEXT,
  depth INTEGER NOT NULL,
  sentence_id INTEGER NOT NULL,
  annotater_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS annotated_relations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  predicate TEXT NOT NULL,
  predicate_index INTEGER NOT NULL,
  argument TEXT NOT NULL,
  argument_index INTEGER NOT NULL,
  relation TEXT NOT NULL,
  relation_word_index TEXT,
  depth INTEGER NOT NULL,
  sentence_id INTEGER NOT NULL,
  annotater_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL
);
